name: general
version: 1.0
description: Config of general benchmark in model evaluation.

device_id: cuda:0
model_format: hf
batch_size: 1
seed: 0
add_bos_token: false
tasks:
  - hellaswag
  - sciq
  - arc_easy
  - arc_challenge
  - openbookqa
  - piqa
  - winogrande
  - lambada_openai
