name: math
version: 1.0
description: Config of math benchmark in model evaluation.

device: cuda:0
model_format: hf
batch_size: 1
seed: 0
add_bos_token: false
tasks:
  - gsm8k
  - mathqa
  - gpqa_diamond_zeroshot
